version: '3'

services:

  osn__users_backend:
    container_name: osn__users_backend
    hostname: 'osn__users_backend'
    build: service-users/backend
    volumes:
      - ./service-users/backend:/backend
    ports:
      - 3000:3000
    depends_on:
      - osn__users_mysql-master
    environment:
      - DB_MASTER_URL=osn__users_mysql-master:3306
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
      - DB_NAME=dbase
      - SERVER_PORT=3000
    networks:
      - otus-social-network

  osn__users_mysql-master:
    image: 'mysql:5.7'
    hostname: 'osn__users_mysql-master'
    container_name: 'osn__users_mysql-master'
    ports:
      - 3307:3306
    volumes:
      - ./service-users/database/master/conf.d:/etc/mysql/mysql.conf.d
      - ./service-users/database/master/data:/var/lib/mysql
      - ./service-users/database/master/log:/var/log/mysql
      - ./service-users/database/master/backup:/backup
      - ./service-users/database/init_sql:/init_sql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dbase
    networks:
      - otus-social-network

  osn__chat_mongo:
    image: mongo:latest
    hostname: 'otn-chat_mongodb'
    container_name: 'otn-chat_mongodb'
    ports:
      - 27017:27017
    volumes:
      - ./service-chat/database/data:/data/db
      - ./service-chat/database/logs:/var/log/mongodb
      - ./service-chat/database/conf/mongo.conf:/etc/mongo.conf
      - ./service-chat/database/init:/init
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: ["mongod", "-f", "/etc/mongo.conf", "--auth"]
    networks:
      - otus-social-network

  osn__chat_backend:
    container_name: osn__chat_backend
    hostname: 'osn__chat_backend'
    build: service-chat/backend
    volumes:
      - ./service-chat/backend:/backend
    ports:
      - 3001:3001
    depends_on:
      - osn__chat_mongo
    environment:
      - DB_URL=osn__chat_mongo:27017
      - DB_USERNAME=root
      - DB_PASSWORD=mongo
      - DB_NAME=chat
      - SERVER_PORT=3001
      - SERVICE_USERS_URL=http://osn__users_backend:3000
    networks:
      - otus-social-network

  osn__nginx:
    container_name: osn_nginx
    image: nginx:latest
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./frontend:/var/www/site
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - osn__users_backend
    ports:
      - 8080:80
    networks:
      - otus-social-network

  osn__npm:
    container_name: osn__npm
    build: frontend
    volumes:
      - ./frontend:/frontend
    networks:
      - otus-social-network

networks:
  otus-social-network:
    external: true
